site_name: Composive - Kotlin Multiplatform UI Library | Available on Maven Central
site_description: >-
  Composive (not composite) is a powerful Kotlin Multiplatform UI library for building responsive 
  and adaptive user interfaces across Android, iOS, Desktop, and Web. Create cross-platform apps 
  with automatic theme adaptation, responsive layouts, and platform-aware components. 
  Available on Maven Central with comprehensive documentation.
  Installation: implementation("io.github.gursimarsingh12:composive-responsive-adaptive:1.0.2")

site_author: Gursimar Singh
site_url: https://gursimarsingh12.github.io/Composive/

repo_name: Gursimarsingh12/Composive
repo_url: https://github.com/Gursimarsingh12/Composive
edit_uri: edit/main/docs-site/docs/

copyright: Copyright &copy; 2024 Gursimar Singh

theme:
  name: material
  custom_dir: overrides
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/comp-logo.svg
  logo: assets/comp-logo.svg
  icon:
    logo: logo

extra:
  homepage: https://gursimarsingh12.github.io/Composive/
  generator: false
  analytics:
    provider: google
    property: G-XXXXXXXXXX # Replace with your Google Analytics ID
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Gursimarsingh12/composive
      name: GitHub Repository
    - icon: fontawesome/solid/download
      link: https://search.maven.org/artifact/io.github.gursimarsingh12/composive-responsive-adaptive
      name: Download from Maven Central
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/gursimar-singh-ba4196204/
      name: LinkedIn Profile
  tags:
    Compose Multiplatform: compose-multiplatform
    Responsive Design: responsive
    Android Development: android
    iOS Development: ios
    Kotlin: kotlin
    UI Library: ui-library
    Cross Platform: cross-platform
    Adaptive UI: adaptive
    Mobile Development: mobile

  # Maven Central specific metadata
  maven_central:
    group_id: io.github.gursimarsingh12
    artifact_id: composive-responsive-adaptive
    version: 1.0.2
    url: https://search.maven.org/artifact/io.github.gursimarsingh12/composive-responsive-adaptive
  
  # SEO enhancements
  meta:
    - name: keywords
      content: >-
        kotlin multiplatform ui library, compose multiplatform, responsive ui, adaptive design, 
        maven central, cross-platform, android, ios, desktop, web, jetpack compose, kotlin library,
        responsive design, adaptive ui, multiplatform development, compose ui, kotlin multiplatform library
    - name: author
      content: Gursimar Singh
    - name: google-site-verification
      content: Y8bdbKUjLWACFdnstWxg8jZ8XVKyGVstMzMpWGmQyds
    - property: og:type
      content: website
    - property: og:title
      content: Composive - Kotlin Multiplatform UI Library | Maven Central
    - property: og:description
      content: >-
        Build responsive cross-platform apps with Composive - now available on Maven Central. 
        Automatic theme adaptation, responsive layouts, and platform-aware components for Android, iOS, Desktop & Web.
    - property: og:image
      content: https://github.com/Gursimarsingh12/composive/raw/main/docs/assets/composive-banner.png
    - property: og:url
      content: https://gursimarsingh12.github.io/composive/
    - name: twitter:card
      content: summary_large_image
    - name: twitter:title
      content: Composive - Kotlin Multiplatform UI Library on Maven Central
    - name: twitter:description
      content: >-
        Create responsive cross-platform UIs with automatic theme adaptation. 
        Now available on Maven Central: implementation("io.github.gursimarsingh12:composive-responsive-adaptive:1.0.2")
    - name: maven-central-group
      content: io.github.gursimarsingh12
    - name: maven-central-artifact
      content: composive-responsive-adaptive
    - name: maven-central-version
      content: 1.0.2
    - property: software:availability
      content: maven-central
    - property: software:license
      content: Apache-2.0

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      lang: en
  - minify:
      minify_html: true
  - meta
  - tags:
      tags_file: tags.md
  - macros
  - git-revision-date-localized:
      enable_creation_date: true
      type: datetime

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - meta
  - toc:
      permalink: true
      title: Table of Contents
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: gursimarsingh12
      repo: composive
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: index.md
  - Why Composive: seo-landing.md
  - Brand: brand-composive.md
  - Getting Started:
    - Overview: overview.md
    - Download from Maven Central: maven-central.md
    - Installation: installation.md
    - Quick Start: getting-started.md
  - Core Concepts:
    - Device Configuration: device-configuration.md
    - Responsive Configuration: configuration.md
    - Typography: typography.md
    - Responsive Dimensions: responsive-dimensions.md
  - Examples:
    - Usage Examples: examples.md
  - API Reference:
    - Complete API: api-reference.md
  - Topics:
    - Kotlin Multiplatform UI Library: kotlin-multiplatform-ui-library.md
    - Compose Multiplatform Responsive: compose-multiplatform-responsive.md
  - Community:
    - Contributing: CONTRIBUTING.md
    - Migration Guide: migration-guide.md
    - Credits: CREDITS.md

extra_css:
  - stylesheets/extra.css
  - stylesheets/seo.css

extra_javascript:
  - javascript/extra.js
  - javascript/seo.js 